before:
  hooks:
  - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - arm64
  - amd64
  - 386
  gobinary: "go1.20.1"
archives:
- replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    386: i386
  format_overrides:
  - goos: windows
    format: zip
  files:
  - config/*
  - resources/ntopng-exporter.service
  - LICENSE*
  - README*
  wrap_in_directory: ntopng-exporter-{{ .Version }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
