ntopng:
  endpoint: "http://127.0.0.1:3000"
  user: admin
  password: admin
  authMethod: cookie # cookie, basic, or none are accepted values

host:
  interfacesToMonitor:
  - enp2s0

metric:
  localSubnetsOnly: # if this is defined, only include the local subnets defined here (greatly reduces number of metrics)
  - "192.168.0.0/24"